build:
    environment:
        python:
            python: 3.6.0
    dependencies:
        before:
            - pip install pymongo
            - pip install motor
check:
    python:
        code_rating: true
        duplicate_code: true
